version: "2"
checks:
    method-count:
        enabled: true
        config:
          threshold: 20
exclude_patterns:
    - "metrics-experimental/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"